### ISSUE TITLE
Flutter compass error appears when i try to build release apk.

### ISSUE THREAD

**Issue by Si11-ibrahim** [Michael-M-aher/location_picker_flutter_map#48]
* What went wrong:
Execution failed for task ':flutter_compass:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR: D:\projects\building-materials\build\flutter_compass\intermediates\merged_res\release\values\values.xml:194: AAPT: error: resource android:attr/lStar not found.

this error occurs when i run flutter build apk command but it builds debug apk. can you help me resolve the problem?

**Comment by IldySilva** [comment]
@Michael-M-aher  pls

**Comment by umit2930** [comment]
@Michael-M-aher  please fix it

**Comment by Michael-M-aher** [comment]
Hello,

Thank you for reaching out. Based on the error you're encountering, it's not specific to the ```location_picker_flutter_map``` package. The error occurs due to a mismatch in the SDK versions or the Android Gradle Plugin (mostly SDK 34), which can happen when a package is using resources or attributes that are not available in the SDK version you're currently targeting.

```gradle
allprojects {
  repositories {
    google()
    mavenCentral()
  }
}

rootProject.buildDir = "../build"

subprojects {
  afterEvaluate { project ->
    if (project.plugins.hasPlugin("com.android.application") ||
        project.plugins.hasPlugin("com.android.library")) {
      project.android {
        compileSdkVersion 34
        buildToolsVersion "34.0.0"
      }
    }
  }
  project.buildDir = "${rootProject.buildDir}/${project.name}"
  project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
  delete rootProject.buildDir
}
```

### Steps:
- **Add this snippet** to your `android/build.gradle`.
- **Run** `flutter clean` and then `flutter build apk --release`.

This should fix the `android:attr/lStar` error during the release build. Let me know if you need further help!
